name: Build and Deploy to Docker
on: push
jobs:
  setup-build-publish-deploy:
    name: Build - Tag - Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: observian/observianpoc.api/observian-poc-api
          tag_with_ref: true
          tag_with_sha: true
          build_args: NUGET_USERNAME=${{ github.actor }},NUGET_API_KEY=${{ secrets.GITHUB_TOKEN }}

